import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HeruSection from '@/components/home/herusec'
import Cards from '@/components/home/cards'
import Form from '@/components/home/form'
import StripePage from '@/components/home/stripe'
import { useRef } from 'react'


export default function Home() {
  const formDiv = useRef()

  const scrollToForm = () => {
    formDiv.current.scrollIntoView({ behavior: "smooth", block: "end", inline: "nearest" });
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id='bbb' className={styles.main}>
        <img onClick={() => { scrollToForm() }} className={styles.absbutton} src='https://o.remove.bg/downloads/ee4ba9c7-dbca-4353-9452-0cdb60165283/Appointment-button-removebg-preview.png' />
        <div className={styles.herosecImg} >
          <HeruSection
            scrollToForm={scrollToForm}
          />
        </div>
        <div className={styles.cards}>
          <Cards />
        </div>
        <div ref={formDiv} className={styles.formContainer}>
          <Form />
        </div>
      </main>
    </>
  )
}
